CONFIG_SYS_BOOTM_LEN="SZ_64M"
CONFIG_SYS_FSL_ESDHC_ADDR=0
CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_USE_SECTOR=y
CONFIG_SYS_LOAD_ADDR=$(CONFIG_LOADADDR)
CONFIG_SYS_FSL_MAX_NUM_OF_SEC=y
CONFIG_SYS_INIT_RAM_ADDR=0x40000000
CONFIG_SYS_CBSIZE="SZ_2K"
CONFIG_SYS_SPL_MALLOC_SIZE="SZ_512K"
CONFIG_SYS_MONITOR_LEN="SZ_512K"
CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR=0x300
CONFIG_SYS_FSL_SEC_ADDR="(CAAM_IPS_BASE_ADDR + CONFIG_SYS_FSL_SEC_OFFSET)"
CONFIG_SPL_BUILD=y
CONFIG_SYS_MALLOC_LEN="SZ_32M"
CONFIG_SYS_I2C_SPEED=100000
CONFIG_MXC_USB_PORTSC="(PORT_PTS_UTMI | PORT_PTS_PTW)"
CONFIG_SYS_FSL_JR0_ADDR="(CONFIG_SYS_FSL_SEC_ADDR + CONFIG_SYS_FSL_JR0_OFFSET)"
CONFIG_USB_MAX_CONTROLLER_COUNT=2
CONFIG_SYS_MAXARGS=64
CONFIG_SYS_UBOOT_BASE="(QSPI0_AMBA_BASE + CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR * 512)"
CONFIG_SPL_STACK=0x920000
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_SYS_FSL_USDHC_NUM=2
CONFIG_FSL_USDHC=y
CONFIG_SYS_MMC_IMG_LOAD_PART=y
CONFIG_SYS_INIT_RAM_SIZE="SZ_512K"
CONFIG_IMX_CONFIG="arch/arm/mach-imx/imx8m/imximage-8mm-lpddr4-fspi.cfg"
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_VAL(option)="config_val(option)"
CONFIG_BOOTCOMMAND=""mmc dev ${mmcdev}; if mmc rescan; then env exists dofitboot || setenv dofitboot 0;env exists doraucboot || setenv doraucboot 0 && saveenv;if test ${doraucboot} = 1; then run raucboot; elif run loadimage; then run mmcboot; else run netboot; fi; fi; " BOOTCOMMAND_APPEND"
CONFIG_SYS_SDRAM_BASE=0x40000000
CONFIG_SYS_FSL_SEC_OFFSET="(0)"
CONFIG_SYS_INIT_SP_ADDR="(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)"
CONFIG_SYS_INIT_SP_OFFSET="(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)"
CONFIG_SPL_ABORT_ON_RAW_IMAGE=y
CONFIG_SYS_I2C=y
CONFIG_SPL_BSS_MAX_SIZE="SZ_8K"
CONFIG_SPL_BSS_START_ADDR=0x910000
CONFIG_SPL_PAD_TO=$(CONFIG_SPL_MAX_SIZE)
CONFIG_MXC_UART_BASE="UART3_BASE_ADDR"
CONFIG_EXTRA_ENV_SETTINGS=""image=Image0console=ttymxc20fdt_addr=0x480000000fdto_addr=0x490000000bootcmd_mfg=fastboot 00bootenv_addr=0x491000000fdt_file=" CONFIG_DEFAULT_FDT_FILE "0ipaddr=192.168.3.110serverip=192.168.3.100netmask=255.225.255.00ip_dyn=no0bootenv=bootenv.txt0mmc_load_bootenv=fatload mmc ${mmcdev}:${mmcpart} ${bootenv_addr} ${bootenv}0mtdids=nor0=30bb0000.spi0spiprobe=true0emmc_dev=20sd_dev=10mmcdev=" __stringify(CONFIG_SYS_MMC_ENV_DEV) "0mmcpart=" __stringify(CONFIG_SYS_MMC_IMG_LOAD_PART) "0mmcroot=20mmcautodetect=yes0mmcargs=setenv bootargs console=${console},${baudrate} root=/dev/mmcblk${mmcdev}p${mmcroot} fsck.repair=yes rootwait rw 0loadimage=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${image}0loadfdt=fatload mmc ${mmcdev}:${mmcpart} ${fdt_addr} ${fdt_file}0mmc_load_overlay=fatload mmc ${mmcdev}:${mmcpart} ${fdto_addr} ${overlay}0mmc_apply_overlays=fdt address ${fdt_addr}; if test ${no_extensions} = 0; then setenv extension_overlay_addr ${fdto_addr}; setenv extension_overlay_cmd 'fatload mmc ${mmcdev}:${mmcpart} ${fdto_addr} ${extension_overlay_name}'; extension scan; extension apply all; fi; if test ${no_overlays} = 0; then for overlay in $overlays; do; if run mmc_load_overlay; then fdt resize ${filesize}; fdt apply ${fdto_addr}; fi; done;fi;0 mmcboot=echo Booting from mmc ...; run spiprobe; if run mmc_load_bootenv; then env import -t ${bootenv_addr} ${filesize}; fi; run mmcargs; run fit_test_and_run_boot; if run loadfdt; then run mmc_apply_overlays; booti ${loadaddr} - ${fdt_addr}; else echo WARN: Cannot load the DT; fi;0 nfsroot=/nfs0netargs=setenv bootargs console=${console},${baudrate} root=/dev/nfs ip=${nfsip} nfsroot=${serverip}:${nfsroot},v3,tcp0net_load_bootenv=${get_cmd} ${bootenv_addr} ${bootenv}0net_load_overlay=${get_cmd} ${fdto_addr} ${overlay}0net_apply_overlays=fdt address ${fdt_addr}; if test ${no_extensions} = 0; then setenv extension_overlay_addr ${fdto_addr}; setenv extension_overlay_cmd '${get_cmd} ${fdto_addr} ${extension_overlay_name}'; extension scan; extension apply all; fi; if test ${no_overlays} = 0; then for overlay in $overlays; do; if run net_load_overlay; then fdt resize ${filesize}; fdt apply ${fdto_addr}; fi; done;fi;0 netboot=echo Booting from net ...; run spiprobe; if test ${ip_dyn} = yes; then setenv nfsip dhcp; setenv get_cmd dhcp; else setenv nfsip ${ipaddr}:${serverip}::${netmask}::eth0:on; setenv get_cmd tftp; fi; if run net_load_bootenv; then env import -t ${bootenv_addr} ${filesize}; fi; run netargs; ${get_cmd} ${loadaddr} ${image}; if ${get_cmd} ${fdt_addr} ${fdt_file}; then run net_apply_overlays; booti ${loadaddr} - ${fdt_addr}; else echo WARN: Cannot load the DT; fi;0raucdev=20" PHYCORE_RAUC_ENV_BOOTLOGIC PHYCORE_FITIMAGE_ENV_BOOTLOGIC"
CONFIG_SYS_FSL_JR1_OFFSET="(0x2000)"
CONFIG_SYS_SPL_MALLOC_START=0x42200000
CONFIG_SPL_MAX_SIZE="(148 * SZ_1K)"
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_LOADADDR=0x40480000
CONFIG_MMCROOT="/dev/mmcblk2p2"
CONFIG_LMB=y
CONFIG_SYS_BARGSIZE=$(CONFIG_SYS_CBSIZE)
CONFIG_IS_ENABLED(option,...)="__concat(__CONFIG_IS_ENABLED_, __count_args(option, ##__VA_ARGS__)) (option, ##__VA_ARGS__)"
CONFIG_SERIAL_TAG=y
CONFIG_SYS_FSL_JR0_OFFSET="(0x1000)"
CONFIG_BOARDDIR="board/phytec/phycore_imx8mm"
CONFIG_MALLOC_F_ADDR=0x912000
